# Generated by Django 4.2.2 on 2024-10-03 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_maillistsetting_periodicity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='parent_mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.maillistsetting', verbose_name='Рассылка'),
        ),
    ]
