# Generated by Django 4.2.2 on 2024-10-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_alter_client_options_alter_mailingattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
