# Generated by Django 4.2.2 on 2024-11-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0005_alter_message_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="maillistsetting",
            name="last_send",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время последней рассылки"
            ),
        ),
        migrations.AddField(
            model_name="maillistsetting",
            name="next_send",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время следующей рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="maillistsetting",
            name="first_send",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время первой рассылки"
            ),
        ),
    ]
