# Generated by Django 4.2.2 on 2024-11-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0008_remove_maillistsetting_receivers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maillistsetting",
            name="receivers",
            field=models.ManyToManyField(
                related_name="Рассылка", to="mail.client", verbose_name="Получатели"
            ),
        ),
    ]
