# Generated by Django 4.2.2 on 2024-11-06 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0010_maillistsetting_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maillistsetting",
            options={
                "permissions": [("set_active_status", "Can activate mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
